#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EvaPost.Resource", IsApplication=true)]

namespace EvaPost
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_from_out_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_bottom = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_in_down = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_in_left = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_in_up = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int slide_out_right = 2130968581;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060004
			public const int botoneraButtonColor = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int botoneraOnPressed = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int cancelButton = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int colorAccent = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int colorPrimary = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int colorPrimaryDark = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int colorText = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int optionButton = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int specialColorText = 2131099654;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_bcsp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_down = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_enter = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_esc = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_multi = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_up = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_color_pressed_grey = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_color_realeased_grey = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_color_released_green = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int button_color_released_pink = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button_color_released_yellow = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int button_pressed_effect_green = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int button_pressed_effect_grey = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int button_pressed_effect_pink = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int button_pressed_effect_yellow = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int categorias_bebida_preparada = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int categorias_bebida_refri = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int categorias_cocina = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int categorias_consumo = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int categorias_ico_next = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int categorias_nevera = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int categorias_otros = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int categorias_panaderia = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int categorias_panaderia_ = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int categorias_reposteria = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int eva2_ico = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int eva_pos_logo_blanco = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int eva_pos_logo_negro = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int fondo_blanco_ppal_02 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ico_ajustes = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ico_arqueo = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ico_articulos = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ico_bsc = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ico_buscar = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ico_buscarfac = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ico_cambprecio = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ico_cancdscto = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ico_cancelar = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ico_cancelaritem = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ico_cantrans = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ico_cliente = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ico_credito = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ico_descabierto = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ico_descuento = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ico_descuentofijo = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ico_devolucion = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ico_efectivo = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ico_enter = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ico_imprimirult = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ico_inventario = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ico_logout = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ico_next = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ico_pagar = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ico_peso = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ico_prestamo = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ico_rebaja = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ico_recogida = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ico_tarjcredito = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ico_vendedor = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ico_vender = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ico_ventaespecial = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ico_volver = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ico_win_menu_snow = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ico_win_x_snow = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ico_x = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int logo_eva_header = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int logo_eva_splash_15 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int logo_redsis = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int p0000003 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int p0000004 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int p0000007 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int p0000008 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int p0000009 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int p0000010 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int p0000012 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int p0000013 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int p0000014 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int p0000015 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int p0000016 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int p0000017 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int p0000018 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int p0000020 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int p0000021 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int p0000024 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int p0000025 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int p0000026 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int p0000029 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int p0000030 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int p0000031 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int p0000032 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int p0000033 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int p0000034 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int p0000035 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int p0000036 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int p0000037 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int p0000038 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int p0000039 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int p0000040 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int p0000042 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int p0000043 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int p0000045 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int p0000046 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int p0000047 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int p0000054 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int p0000055 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int p0000056 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int p0000057 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int p0000058 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int p0000060 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int p0000061 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int p0000062 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int p0000065 = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int p0000066 = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int p0000069 = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int p0000072 = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int p0000073 = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int p0000075 = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int p0000077 = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int p0000078 = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int p0000079 = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int p0000085 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int p0000087 = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int p0000088 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int p0000089 = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int p0000091 = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int p0000092 = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int p0000093 = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int p0000094 = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int p0000105 = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int p0000106 = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int p0000107 = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int p0000108 = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int p0000111 = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int p0000112 = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int p0000123 = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int p0000124 = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int p0000129 = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int p0000130 = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int p0000131 = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int p0000134 = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int p0000136 = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int p0000137 = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int p0000138 = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int p0000139 = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int p0000140 = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int p0000202 = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int p0000203 = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int p0000204 = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int p0000206 = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int p0000237 = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int p0000239 = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int p0000243 = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int p0000300 = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int p0000304 = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int p0000305 = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int p0000306 = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int p0000307 = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int p0000308 = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int p0000309 = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int p0000310 = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int p0000311 = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int p0000312 = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int p0000313 = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int p0000316 = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int p0000317 = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int p0000318 = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int p0000319 = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int p0000320 = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int p0000321 = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int p0000338 = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int p0000339 = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int p0000340 = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int p0000341 = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int p0000342 = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int p0000357 = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int p0000358 = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int p0000359 = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int p0000360 = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int p0000361 = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int p0000364 = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int p0000365 = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int p0000366 = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int p0000368 = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int p0000374 = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int p0000375 = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int p0000376 = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int p0000377 = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int p0000378 = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int p0000379 = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int p0000381 = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int p0000382 = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public const int p0000383 = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public const int p0000384 = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public const int p0000385 = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public const int p0000403 = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public const int p0000404 = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public const int p0000413 = 2130837701;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int TAG_ONLINE_ID = 2131230720;
			
			// aapt resource value: 0x7f08001c
			public const int aceptar = 2131230748;
			
			// aapt resource value: 0x7f08001f
			public const int articleCode = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int backToPanel = 2131230750;
			
			// aapt resource value: 0x7f080014
			public const int borrar = 2131230740;
			
			// aapt resource value: 0x7f080023
			public const int buttonShowTirillaDePago = 2131230755;
			
			// aapt resource value: 0x7f080035
			public const int buttons_fragment = 2131230773;
			
			// aapt resource value: 0x7f08000b
			public const int cancelButton = 2131230731;
			
			// aapt resource value: 0x7f080025
			public const int cantidadProducto = 2131230757;
			
			// aapt resource value: 0x7f08003a
			public const int changeButoneraSize = 2131230778;
			
			// aapt resource value: 0x7f080008
			public const int cocinaButton = 2131230728;
			
			// aapt resource value: 0x7f080039
			public const int columns = 2131230777;
			
			// aapt resource value: 0x7f08002e
			public const int configuration = 2131230766;
			
			// aapt resource value: 0x7f080036
			public const int configurationLayout1 = 2131230774;
			
			// aapt resource value: 0x7f080037
			public const int configurationLayout2 = 2131230775;
			
			// aapt resource value: 0x7f080002
			public const int consumoButton = 2131230722;
			
			// aapt resource value: 0x7f080010
			public const int escape = 2131230736;
			
			// aapt resource value: 0x7f080030
			public const int fragment_composition = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int fragment_container = 2131230769;
			
			// aapt resource value: 0x7f080005
			public const int hojaldresButton = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int lacteosButton = 2131230729;
			
			// aapt resource value: 0x7f08001d
			public const int listaArticulos = 2131230749;
			
			// aapt resource value: 0x7f08002b
			public const int loginButton = 2131230763;
			
			// aapt resource value: 0x7f080028
			public const int login_title = 2131230760;
			
			// aapt resource value: 0x7f08002f
			public const int mainLayout = 2131230767;
			
			// aapt resource value: 0x7f08002c
			public const int mensajeError = 2131230764;
			
			// aapt resource value: 0x7f080018
			public const int multiplicar = 2131230744;
			
			// aapt resource value: 0x7f080006
			public const int neveraButton = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int noSell = 2131230730;
			
			// aapt resource value: 0x7f080020
			public const int nombreArticulo = 2131230752;
			
			// aapt resource value: 0x7f080026
			public const int nombreProducto = 2131230758;
			
			// aapt resource value: 0x7f080019
			public const int number0 = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int number00 = 2131230746;
			
			// aapt resource value: 0x7f08000d
			public const int number1 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int number2 = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int number3 = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int number4 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int number5 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int number6 = 2131230739;
			
			// aapt resource value: 0x7f080015
			public const int number7 = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int number8 = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int number9 = 2131230743;
			
			// aapt resource value: 0x7f080034
			public const int numberPadFragment = 2131230772;
			
			// aapt resource value: 0x7f080033
			public const int operatorView = 2131230771;
			
			// aapt resource value: 0x7f080004
			public const int otrosButton = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int panaderiaButton = 2131230723;
			
			// aapt resource value: 0x7f080032
			public const int panel = 2131230770;
			
			// aapt resource value: 0x7f08002a
			public const int password = 2131230762;
			
			// aapt resource value: 0x7f08000c
			public const int payButton = 2131230732;
			
			// aapt resource value: 0x7f080021
			public const int precio_articulo = 2131230753;
			
			// aapt resource value: 0x7f080024
			public const int precio_total = 2131230756;
			
			// aapt resource value: 0x7f080001
			public const int preparadasButton = 2131230721;
			
			// aapt resource value: 0x7f08001b
			public const int punto = 2131230747;
			
			// aapt resource value: 0x7f080007
			public const int reposteriaButton = 2131230727;
			
			// aapt resource value: 0x7f080038
			public const int rows = 2131230776;
			
			// aapt resource value: 0x7f08002d
			public const int sell = 2131230765;
			
			// aapt resource value: 0x7f080022
			public const int texto_advertencia = 2131230754;
			
			// aapt resource value: 0x7f080029
			public const int username = 2131230761;
			
			// aapt resource value: 0x7f080027
			public const int valorProducto = 2131230759;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FragmentoBotonera = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FragmentoNumberPad = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FragmentoTirillaDePago = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FragmentoTirillaPanelDePago = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FragmentoVistaOperador = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int list_item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListaArticuloItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Menu = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int PanelDeVenta = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PanelDeVenta2 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PantallaConfiguracion = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070011
			public const int TECLADO_PRINCIPAL = 2131165201;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int canc_item = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int cancelar = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int cocina = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int cons_precio = 2131165196;
			
			// aapt resource value: 0x7f070003
			public const int consumo = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int devoluci_n = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int hello_blank_fragment = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int hojaldres = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int lacteos = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int nevera = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int no_venta = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int otros = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int pagar = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int panader_a = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int preparadas = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int reposter_a = 2131165191;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int teclado = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
